# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

staging:
  adapter: mysql
  database: db_primary
  username: propel
  password: zeal919luxePX
  socket: /var/run/mysqld/mysqld.sock
    
production:
  adapter: mysql
  database: db_primary
  username: propel
  password: zeal919luxePX
  socket: /var/run/mysqld/mysqld.sock